/*
Generate JSON file with version numbers for mangrove-core and mangrove-strats.
*/
import path from "path";
import fs from "fs";

import mangroveCorePackageJson from "@mangrovedao/mangrove-core/package.json";
import mangroveStratsPackageJson from "@mangrovedao/mangrove-strats/package.json";

async function main() {
  const outFile = path.join(
    process.cwd(),
    "src/constants",
    "contractPackageVersions.json"
  );

  fs.writeFileSync(
    outFile,
    JSON.stringify(
      {
        COMMENT:
          "This file is generated by the build system. Do not modify it manually.",
        "mangrove-core": mangroveCorePackageJson.version,
        "mangrove-strats": mangroveStratsPackageJson.version,
      },
      null,
      2
    )
  );
}

main()
  .then(() => {
    process.exit(0);
  })
  .catch(console.error);
