/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MgvOracle } from "./MgvOracle";
export * as factories from "./factories";
export { MgvOracle__factory } from "./factories/MgvOracle__factory";
